### ISSUE TITLE
Небольшие проблемы в тексте

### ISSUE THREAD

**Issue by Nklya** [Mykolaichenko/devopsfactors#8]
Привет.
Отличный список, спасибо!

Хотел бы отметить места, которые мне кажутся странными:
1. Слово "правильной" по отношению к культуре звучит странно. Возможно его стоит заменить на "здоровой" или вообще убрать
2. Есть несколько использований прямого произношения английских слов, например "предиктить", "роадмап", "мувмент". Возможно их стоит заменить на русскоязычные аналоги или написать по-английски
3. Ну и опечатка в фразе "Желательно что б был один и тот же менеджер", там видимо имелось в виду "чтобы был один"

**Comment by Mykolaichenko** [comment]
@Nklya Thanks! That's very reasonable. Could you please make PR with following changes?

**Comment by Nklya** [comment]
Of course, maybe next year)
